version: "2.1"
services:
  haproxy:
    image: eeacms/haproxy:1.8-1.3
    ports:
    - 80:8080
    - 1936:1936
    depends_on:
    - plone
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS_PORT: "8080"
      BACKENDS: "plone"
      DNS_ENABLED: "True"
      TZ: "Europe/Copenhagen"

  shell:
    image: "${IMAGE:-eeacms/plone}"
    depends_on:
      - memcached
      - postfix
      - zeo
      - postgres
    environment:
      # ZOPE_MODE: "rel_client"
      ZOPE_MODE: "${ZOPE_MODE:-zeo_client}"
      TZ: "Europe/Copenhagen"
    tty: true
    stdin_open: true
    command: cat
    ports:
    - 3080:8080

  plone:
    image: "${IMAGE:-eeacms/plone}"
    depends_on:
      - memcached
      - postfix
      - zeo
      - postgres
    environment:
      # ZOPE_MODE: "rel_client"
      ZOPE_MODE: "${ZOPE_MODE:-zeo_client}"
      TZ: "Europe/Copenhagen"

  zeo:
    image: "${IMAGE:-eeacms/plone}"
    environment:
      ZOPE_MODE: "zeo"
      TZ: "Europe/Copenhagen"
    volumes:
      - zeo:/data
    command:
      - zeo

  postgres:
    image: eeacms/postgres:9.6-3.5
    environment:
      POSTGRES_DBNAME: "datafs zasync"
      POSTGRES_DBUSER: "zope"
      POSTGRES_DBPASS: "zope"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "Europe/Bucharest"
    volumes:
    - postgres:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5.12
    command:
    - "-m"
    - "1024"
    environment:
      TZ: "Europe/Copenhagen"

  postfix:
    image: eeacms/postfix:2.10-3.3
    environment:
      MTP_HOST: "example.com"
      TZ: "Europe/Copenhagen"

volumes:
  zeo:
    driver: local
  postgres:
    driver: local
