version: "3.8"
services:
  varnish:
    image: eea-varnish:4.1
    networks: 
    - emc
    ports:
    - "8580:6081"
    - "6085:6085"
    depends_on:
    - haproxy

    environment:
      BACKENDS: "haproxy"
      BACKENDS_PORT: "8581"
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"

  haproxy:
    image: eea-haproxy:1.8.22
    networks: 
    - emc
    ports:
    - 8581:5000
    - 1936:1936
    depends_on:
    - plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"

  plone:
    image: registry.cn-hangzhou.aliyuncs.com/plone/plone516-emc:5.0
    networks: 
    - emc
    ports:
    - 8080:8080
    depends_on:
    - zeoserver
    - oracledb
    environment:
    - ZEO_ADDRESS=zeoserver:8200

  zeoserver:
    image: registry.cn-hangzhou.aliyuncs.com/plone/plone516-emc:5.0
    networks: 
    - emc
    ports:
    - 8200:8200
    command: zeo
    volumes:
    - data:/data

  oracledb:
    image: registry.cn-hangzhou.aliyuncs.com/oracle-db/oracledb:12.2.0.1-se2
    networks: 
    - emc

    volumes:
      - /opt/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8380:8080
      - 5500:5500


networks:
  emc:

volumes:
  data:
