plone:
  build: .
  user: 1000
  environment:
  - INDEX=
      http://eggrepo.apps.eea.europa.eu/pypi/
  - FIND_LINKS=
      http://eggrepo.apps.eea.europa.eu/simple
      http://dist.plone.org/thirdparty/
      http://pypi.python.org/pypi
