plone:
  image: eeacms/plone:5.0
  ports:
  - "8080:8080"
  links:
  - zeoserver
  environment:
  - BUILDOUT_ZEO_CLIENT=True
  - BUILDOUT_ZEO_ADDRESS=zeoserver:8100

zeoserver:
  image: eeacms/zeoserver
